# Generated by Django 4.1.7 on 2023-02-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
