# Generated by Django 4.1.7 on 2023-02-26 07:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication_feature', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='close_friends',
            field=models.ManyToManyField(related_name='close_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
